services:
    wtk_db_mysql:
        platform: linux/amd64
        image: mysql:8.3
        container_name: kwik_mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password --secure-file-priv='/var/lib/mysql' --sql-mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'
        environment:
          MYSQL_ROOT_PASSWORD: 'LowCodeViaWTK'
          TZ: 'America/Phoenix'
        ports:
          - '3306:3306'
        volumes:
          - ./Mounts/mydata:/var/lib/mysql
    web:
        platform: linux/amd64
        container_name: kwik_apache_php
        build:
          context: .
          dockerfile: PHP.Dockerfile
        ports:
          - '80:80'
          - '443:443'
        volumes:
          - ./app/public:/var/www/html
        depends_on:
          - wtk_db_mysql
        env_file:
          - ./phpMySQL.env
    phpmyadmin:
        image: phpmyadmin
        container_name: kwik_phpmyadmin
        restart: always
        links:
            - wtk_db_mysql
        environment:
            PMA_HOST: wtk_db_mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        ports:
            - 8080:80
